spring:
  application:
          name: Gabbi2
  datasource:
    url: jdbc:mysql://localhost:3306/gabbi_music
    username: gabbi2
    password: gabbi2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

server:
  servlet:
    context-path: /
    session:
      timeout: 60
  error:
    path: /error
#  address: 172.16.1.101
  tomcat:
    threads:
      max: 100
    uri-encoding: UTF-8
logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    path: logs/
  logback:
    rollback:
      rolling policy:
              max-file-size: 5MB
              max-history: 3

music:
  upload-dir: uploads/
mv:
  upload-dir: uploads/mv


