spring:
  application:
          name: Gabbi2
  datasource:
    url: jdbc:mysql://localhost:3306/gabbi_music
    username: gabbi2
    password: gabbi2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

server:
  servlet:
    context-path: /
    session:
      timeout: 60
  error:
    path: /error
#  address: address
  tomcat:
    threads:
      max: 100
    uri-encoding: UTF-8

music:
  upload-dir: uploads/